extends: default
rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
    indent-sequences: whatever
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
ignore: |
  .github/
